/**
 * Source of the two scripts the RoSignal Studio plugin inserts into a place.
 * The website never shows the module source any more — the plugin owns it.
 */

import { DEFAULT_INGEST_SETTINGS, MODULE_VERSION, type IngestSettings } from "./ingest";

export const MODULE_NAME = "RoSignal";
export const HANDLERS_NAME = "RoSignalHandlers";
/** Starter demo UI, inserted as a child of the handlers script. Deletable. */
export const DEMO_NAME = "RoSignalDemo";
/** Optional, developer-owned settings module. The plugin never overwrites it. */
export const SETTINGS_NAME = "RoSignalSettings";
/** Fixed MessagingService topic every RoSignal payload travels on. */
export const GAME_TOPIC = "RoSignal";

export function moduleSource(
  origin: string,
  gameId: string,
  gameKey: string,
  ingest: IngestSettings = DEFAULT_INGEST_SETTINGS,
): string {
  const settings = ingest;
  return `--[[ RoSignal runtime — inserted and updated by the RoSignal Studio plugin.
\tDo not edit this file. Put your own code in ${HANDLERS_NAME}. ]]

local HttpService = game:GetService("HttpService")
local MessagingService = game:GetService("MessagingService")

local GAME_KEY = "${gameKey}"
local CONFIG_URL = "${origin}/api/public/config/${gameId}"
local AGG_URL = "${origin}/api/public/agg/${gameId}"
local ACK_URL = "${origin}/api/public/ack"

local TRAITS_URL = "${origin}/api/public/traits/${gameId}"
local GROUPS_URL = "${origin}/api/public/groups/${gameId}"

local Players = game:GetService("Players")
local ServerScriptService = game:GetService("ServerScriptService")

local RoSignal = {}

local sampleRate = ${settings.sampleRate}
local mapCell = ${settings.mapCellSize}

-- Map settings. Edit ServerScriptService.${SETTINGS_NAME} to change these —
-- this file is regenerated by the plugin, that one is yours.
local mapSettings = { MapByDefault = true, MapEvents = nil, MapExclude = {} }
do
\tlocal module = ServerScriptService:FindFirstChild("${SETTINGS_NAME}")
\tif module and module:IsA("ModuleScript") then
\t\tlocal ok, loaded = pcall(require, module)
\t\tif ok and type(loaded) == "table" then
\t\t\tfor key, value in pairs(loaded) do mapSettings[key] = value end
\t\tend
\tend
end

local function listHas(list, name)
\tif type(list) ~= "table" then return false end
\tfor _, entry in ipairs(list) do
\t\tif entry == name then return true end
\tend
\treturn false
end

-- Should this event carry a position (and so show up on the map)?
local function wantsMap(name, options)
\tif type(options) == "table" and options.map ~= nil then
\t\treturn options.map and true or false
\tend
\tif listHas(mapSettings.MapExclude, name) then return false end
\tif type(mapSettings.MapEvents) == "table" then return listHas(mapSettings.MapEvents, name) end
\treturn mapSettings.MapByDefault ~= false
end

local cache = {}
local overrides = {}
-- Events a funnel depends on: never sampled, always sent whole.
local fullEvents = {}
-- Active percentage rollouts: key → { percent = n, value = v }.
local rollouts = {}
local anyChange = {}
local keyChange = {}
local anyMessage = {}
local topicMessage = {}

local function fire(list, ...)
\tfor _, fn in ipairs(list) do
\t\ttask.spawn(fn, ...)
\tend
end

-- 1. Live settings -----------------------------------------------------------

local function applyValues(values)
\tfor key, value in pairs(values) do
\t\tlocal old = cache[key]
\t\tif old ~= value then
\t\t\tcache[key] = value
\t\t\tfire(anyChange, key, value, old)
\t\t\tif keyChange[key] then fire(keyChange[key], value, old) end
\t\tend
\tend
end

local function applyOverrides(map)
\tfor userId, values in pairs(map) do
\t\toverrides[tostring(userId)] = values
\tend
end

-- Deterministic bucket (0-99) for one player on one setting. The same player
-- always lands in the same bucket, so rollout groups stay stable across
-- sessions. Keep in sync with rolloutBucket() in config.server.ts.
local function bucketFor(key, userId)
\tlocal input = key .. ":" .. tostring(userId)
\tlocal h = 0
\tfor i = 1, #input do
\t\th = (h * 31 + string.byte(input, i)) % 4294967296
\tend
\treturn h % 100
end

-- Replace the full rollout map.
local function applyRollouts(map)
\trollouts = {}
\tfor key, entry in pairs(map) do
\t\tif type(entry) == "table" then
\t\t\trollouts[key] = {
\t\t\t\tpercent = tonumber(entry.percent) or 0,
\t\t\t\tvalue = entry.value,
\t\t\t\tmembers = type(entry.members) == "table" and entry.members or nil,
\t\t\t}
\t\tend
\tend
end

local function clamp(value, low, high, fallback)
\tlocal n = tonumber(value)
\tif n == nil or n ~= n then return fallback end
\treturn math.max(low, math.min(high, n))
end

-- GETs the full config payload. Returns the decoded body, or nil on failure.
local function requestConfig()
\tlocal ok, res = pcall(function()
\t\treturn HttpService:RequestAsync({
\t\t\tUrl = CONFIG_URL,
\t\t\tMethod = "GET",
\t\t\tHeaders = {
\t\t\t\t["x-rosignal-key"] = GAME_KEY,
\t\t\t\t-- Lets RoSignal notice when you publish a new version from Studio.
\t\t\t\t["x-rosignal-place-version"] = tostring(game.PlaceVersion),
\t\t\t},
\t\t})
\tend)
\tif not ok or not res or not res.Success then return nil end
\tlocal decoded = nil
\tlocal parsed = pcall(function() decoded = HttpService:JSONDecode(res.Body) end)
\tif not parsed or type(decoded) ~= "table" then return nil end
\treturn decoded
end

local function applyIngestSettings(body)
\tif type(body.ingest) == "table" then
\t\t-- Clamped: a bad or tampered value must never break tracking.
\t\tsampleRate = clamp(body.ingest.sampleRate, 0, 1, sampleRate)
\t\tmapCell = clamp(body.ingest.mapCell, 1, 512, mapCell)
\tend
end

local function fetchConfig()
\tlocal body = requestConfig()
\tif body then
\t\tcache = body.config or {}
\t\toverrides = body.overrides or {}
\t\tfullEvents = {}
\t\tfor _, name in ipairs(body.fullEvents or {}) do fullEvents[name] = true end
\t\tapplyIngestSettings(body)
\t\trollouts = {}
\t\tapplyRollouts(body.rollouts or {})
\telse
\t\twarn("[RoSignal] could not load settings — is Allow HTTP Requests on?")
\tend
end
fetchConfig()

-- Studio never receives MessagingService pushes (Roblox keeps Studio sessions
-- separate from live servers), so there we poll instead: a refetch about once a
-- second that runs the same change handlers a live push would, so testing feels
-- live. If requests start failing we quietly slow down. Live servers keep using
-- instant pushes and never poll.
-- Announcements: topic-less messages sent from Messages, rules, or the guided
-- setup. They reach Studio too (through the config poll), not just live servers.
local announcementHandlers = {}

local function fireAnnouncements(text)
\tfor _, fn in ipairs(announcementHandlers) do
\t\ttask.spawn(fn, text)
\tend
end

local inStudio = game:GetService("RunService"):IsStudio()
if inStudio then
\t-- Announcements arrive on the config poll; remember which ones already
\t-- showed so a slow acknowledgement never double-displays them.
\tlocal seenAnnouncements = {}
\ttask.spawn(function()
\t\tlocal wait = 1
\t\twhile true do
\t\t\ttask.wait(wait)
\t\t\tlocal ok, body = pcall(requestConfig)
\t\t\tif ok and body then
\t\t\t\twait = 1
\t\t\t\tapplyValues(body.config or {})
\t\t\t\tapplyOverrides(body.overrides or {})
\t\t\t\tif body.rollouts ~= nil then applyRollouts(body.rollouts) end
\t\t\t\tapplyIngestSettings(body)
\t\t\t\tfor _, item in ipairs(body.announcements or {}) do
\t\t\t\t\tif item.id and not seenAnnouncements[item.id] then
\t\t\t\t\t\tseenAnnouncements[item.id] = true
\t\t\t\t\t\tfireAnnouncements(tostring(item.text or ""))
\t\t\t\t\t\ttask.spawn(function()
\t\t\t\t\t\t\tpcall(function()
\t\t\t\t\t\t\t\tHttpService:RequestAsync({
\t\t\t\t\t\t\t\t\tUrl = ACK_URL,
\t\t\t\t\t\t\t\t\tMethod = "POST",
\t\t\t\t\t\t\t\t\tHeaders = { ["Content-Type"] = "application/json", ["x-rosignal-key"] = GAME_KEY },
\t\t\t\t\t\t\t\t\tBody = HttpService:JSONEncode({ announcementId = item.id, jobId = game.JobId }),
\t\t\t\t\t\t\t\t})
\t\t\t\t\t\t\tend)
\t\t\t\t\t\tend)
\t\t\t\t\tend
\t\t\t\tend
\t\t\telse
\t\t\t\twait = math.min(wait * 2, 30)
\t\t\tend
\t\tend
\tend)
end

--- Read a setting, falling back to a default.
function RoSignal.Get(key, default)
\tlocal value = cache[key]
\tif value == nil then return default end
\treturn value
end

--- Deprecated alias for Get, kept so older copied snippets keep working.
RoSignal.GetConfig = RoSignal.Get


-- True when this player receives the rollout value: either they are inside the
-- percentage bucket, or they are in the segment the rollout targets.
local function inRollout(key, userId)
\tlocal rollout = rollouts[key]
\tif rollout == nil then return false end
\tif rollout.members ~= nil then
\t\treturn rollout.members[tostring(userId)] == true
\tend
\treturn bucketFor(key, userId) < rollout.percent
end

--- Read a setting for one player: their override when set, then their rollout
--- group when the setting has an active rollout, otherwise the global value.
function RoSignal.GetFor(player, key, default)
\tlocal userId = typeof(player) == "Instance" and player.UserId or player
\tlocal forPlayer = overrides[tostring(userId)]
\tif forPlayer ~= nil and forPlayer[key] ~= nil then
\t\treturn forPlayer[key]
\tend
\tif inRollout(key, userId) then
\t\treturn rollouts[key].value
\tend
\treturn RoSignal.Get(key, default)
end

--- True when this player is on an override instead of the global value.
function RoSignal.HasOverride(player, key)
\tlocal userId = typeof(player) == "Instance" and player.UserId or player
\tlocal forPlayer = overrides[tostring(userId)]
\treturn forPlayer ~= nil and forPlayer[key] ~= nil
end

--- True when this player is receiving a setting's rollout value.
function RoSignal.InRollout(player, key)
\tlocal userId = typeof(player) == "Instance" and player.UserId or player
\treturn inRollout(key, userId)
end

-- 1b. Player traits ----------------------------------------------------------

local traitQueue = {}
local traitFlushScheduled = false

local function flushTraits()
\ttraitFlushScheduled = false
\tlocal batch = {}
\tfor userId, traits in pairs(traitQueue) do
\t\ttable.insert(batch, { playerId = userId, traits = traits })
\tend
\ttraitQueue = {}
\tif #batch == 0 then return end
\ttask.spawn(function()
\t\tpcall(function()
\t\t\tHttpService:RequestAsync({
\t\t\t\tUrl = TRAITS_URL,
\t\t\t\tMethod = "POST",
\t\t\t\tHeaders = { ["Content-Type"] = "application/json", ["x-rosignal-key"] = GAME_KEY },
\t\t\t\tBody = HttpService:JSONEncode({ players = batch }),
\t\t\t})
\t\tend)
\tend)
end

--- Describe a player so segments can use it: RoSignal.SetTraits(player, { vip = true }).
--- Traits are merged, batched, and sent a few seconds later.
function RoSignal.SetTraits(player, traits)
\tif type(traits) ~= "table" then return end
\tlocal userId = tostring(typeof(player) == "Instance" and player.UserId or player)
\tlocal pending = traitQueue[userId] or {}
\tfor key, value in pairs(traits) do
\t\tpending[key] = value
\tend
\ttraitQueue[userId] = pending
\tif not traitFlushScheduled then
\t\ttraitFlushScheduled = true
\t\ttask.delay(5, flushTraits)
\tend
end

--- Run now with the current value, then again on every change.
function RoSignal.Bind(key, fn)
\tkeyChange[key] = keyChange[key] or {}
\ttable.insert(keyChange[key], fn)
\ttask.spawn(fn, cache[key])
end

--- Run only when one setting changes.
function RoSignal.OnKeyChange(key, fn)
\tkeyChange[key] = keyChange[key] or {}
\ttable.insert(keyChange[key], fn)
end

--- OnChange(fn) for every setting, or OnChange({ Damage = fn, Speed = fn }).
function RoSignal.OnChange(target, maybeFn)
\tif type(target) == "table" then
\t\tfor key, fn in pairs(target) do RoSignal.OnKeyChange(key, fn) end
\telseif type(maybeFn) == "function" then
\t\tRoSignal.OnKeyChange(target, maybeFn)
\telse
\t\ttable.insert(anyChange, target)
\tend
end

-- 2. Messages ----------------------------------------------------------------

local function ack(runId, actionId)
\ttask.spawn(function()
\t\tpcall(function()
\t\t\tHttpService:RequestAsync({
\t\t\t\tUrl = ACK_URL,
\t\t\t\tMethod = "POST",
\t\t\t\tHeaders = { ["Content-Type"] = "application/json", ["x-rosignal-key"] = GAME_KEY },
\t\t\t\tBody = HttpService:JSONEncode({ runId = runId, actionId = actionId, jobId = game.JobId }),
\t\t\t})
\t\tend)
\tend)
end

--- OnMessage("StartEvent", fn) for one topic, or OnMessage(fn) for all of them.
--- Handlers receive (data, topic, player) — player is set for player-targeted sends.
function RoSignal.OnMessage(target, maybeFn)
\tif type(target) == "function" then
\t\ttable.insert(anyMessage, target)
\telse
\t\ttopicMessage[target] = topicMessage[target] or {}
\t\ttable.insert(topicMessage[target], maybeFn)
\tend
end

--- OnAnnouncement(fn) — fn(text) runs when RoSignal announces something.
function RoSignal.OnAnnouncement(fn)
\ttable.insert(announcementHandlers, fn)
end

-- 2b. Moderation --------------------------------------------------------------
-- Bans are enforced by Roblox itself (RoSignal uses Roblox's restriction API),
-- so this script only handles live kicks.

local function handleModeration(decoded)
\tif decoded.action ~= "kick" then return end
\tlocal userId = tonumber(decoded.userId)
\tif not userId then return end

\tlocal player = Players:GetPlayerByUserId(userId)
\tif not player then return end

\tplayer:Kick(decoded.reason ~= "" and decoded.reason or "You were removed from this server.")

\tif decoded.actionId then ack(nil, decoded.actionId) end
end

-- Live servers only: Studio never receives these pushes, and the poll loop
-- above already keeps Studio settings fresh.
if not inStudio then
MessagingService:SubscribeAsync("${GAME_TOPIC}", function(message)
\tlocal raw = message.Data
\tlocal ok, decoded = pcall(function() return HttpService:JSONDecode(raw) end)

\tif ok and type(decoded) == "table" and decoded.kind == "config" then
\t\tapplyValues(decoded.values or {})
\t\tapplyOverrides(decoded.overrides or {})
\t\tif decoded.rollouts ~= nil then applyRollouts(decoded.rollouts) end
\t\treturn
\tend

\tif ok and type(decoded) == "table" and decoded.kind == "moderation" then
\t\thandleModeration(decoded)
\t\treturn
\tend

\tif ok and type(decoded) == "table" and decoded.kind == "announcement" then
\t\tfireAnnouncements(tostring(decoded.text or ""))
\t\treturn
\tend



\tlocal topic, data, target = nil, raw, nil
\tif ok and type(decoded) == "table" and decoded.kind == "message" then
\t\ttopic, data, target = decoded.topic, decoded.data, decoded.target
\tend

\t-- Segment sends run once per matching player in this server.
\tif target and target.kind == "segment" then
\t\tlocal matched = {}
\t\tfor _, userId in ipairs(target.userIds or {}) do
\t\t\tlocal found = Players:GetPlayerByUserId(tonumber(userId) or 0)
\t\t\tif found then table.insert(matched, found) end
\t\tend
\t\tif #matched == 0 then return end
\t\tif target.runId then ack(target.runId) end
\t\tfor _, found in ipairs(matched) do
\t\t\tif topic and topicMessage[topic] then fire(topicMessage[topic], data, topic, found) end
\t\t\tfire(anyMessage, data, topic, found)
\t\tend
\t\treturn
\tend

\t-- Targeted sends only run in the server that holds the player.
\tlocal player = nil
\tif target and target.kind and target.kind ~= "all" then
\t\tlocal userId = tonumber(target.userId)
\t\tplayer = userId and Players:GetPlayerByUserId(userId) or nil
\t\tif not player then return end
\t\tif target.runId then ack(target.runId) end
\t\tif target.kind ~= "player" then player = nil end
\tend

\tif topic and topicMessage[topic] then fire(topicMessage[topic], data, topic, player) end
\tfire(anyMessage, data, topic, player)
end)

-- Legacy channel: older places subscribed to a separate config topic.
MessagingService:SubscribeAsync("${GAME_TOPIC}:config", function(message)
\tlocal ok, decoded = pcall(function() return HttpService:JSONDecode(message.Data) end)
\tif ok and type(decoded) == "table" and decoded.kind == "config" then
\t\tapplyValues(decoded.values or {})
\t\tapplyOverrides(decoded.overrides or {})
\t\tif decoded.rollouts ~= nil then applyRollouts(decoded.rollouts) end
\tend
end)
end

-- 3. Events (v${MODULE_VERSION}) ---------------------------------------------------------
-- Events are counted here, in the game, and merged across every server with
-- MemoryStore. RoSignal receives one small summary per minute instead of every
-- single event, so counts stay exact while costing almost nothing to store.

local MemoryStoreService = game:GetService("MemoryStoreService")

local FLUSH_SECONDS = ${settings.flushSeconds}
local MAX_PROP_KEYS = ${settings.maxPropKeys}
-- A closed minute waits this long for stragglers before one server sends it.
local SEND_DELAY = 45
local SEP = "\\30"

local store = nil
do
\tlocal ok, map = pcall(function() return MemoryStoreService:GetHashMap("RoSignalAgg") end)
\tif ok then store = map end
end

-- pending[bucketSeconds] = { counters = {}, players = {}, cells = {}, samples = {} }
local pending = {}
local awaitingSend = {}

local function bucketNow()
\treturn math.floor(os.time() / 60) * 60
end

local function stateFor(bucket)
\tlocal state = pending[bucket]
\tif not state then
\t\tstate = { counters = {}, players = {}, cells = {}, samples = {} }
\t\tpending[bucket] = state
\tend
\treturn state
end

local function bumpCounter(state, name, key, value, numeric)
\tlocal id = name .. SEP .. key .. SEP .. value
\tlocal row = state.counters[id]
\tif not row then
\t\trow = { n = name, k = key, v = value, c = 0 }
\t\tstate.counters[id] = row
\tend
\trow.c += 1
\tif numeric ~= nil then
\t\trow.s = (row.s or 0) + numeric
\t\trow.mn = row.mn == nil and numeric or math.min(row.mn, numeric)
\t\trow.mx = row.mx == nil and numeric or math.max(row.mx, numeric)
\tend
end

local function mergeCounters(into, from)
\tfor id, row in pairs(from) do
\t\tlocal target = into[id]
\t\tif not target then
\t\t\tinto[id] = row
\t\telse
\t\t\ttarget.c += row.c
\t\t\tif row.s then target.s = (target.s or 0) + row.s end
\t\t\tif row.mn then target.mn = target.mn == nil and row.mn or math.min(target.mn, row.mn) end
\t\t\tif row.mx then target.mx = target.mx == nil and row.mx or math.max(target.mx, row.mx) end
\t\tend
\tend
end

local function mergeCounts(into, from)
\tfor id, value in pairs(from) do
\t\tinto[id] = (into[id] or 0) + value
\tend
end

local function mergeState(into, from)
\tinto.counters = into.counters or {}
\tinto.players = into.players or {}
\tinto.cells = into.cells or {}
\tmergeCounters(into.counters, from.counters or {})
\tmergeCounts(into.players, from.players or {})
\tmergeCounts(into.cells, from.cells or {})
\treturn into
end

-- Turn the in-game tables into the wire shape RoSignal expects.
local function encode(bucket, state, samples)
\tlocal counters, players, cells = {}, {}, {}
\tlocal iso = DateTime.fromUnixTimestamp(bucket):ToIsoDate()
\tfor _, row in pairs(state.counters or {}) do
\t\ttable.insert(counters, {
\t\t\tbucket = iso, name = row.n, prop_key = row.k, prop_value = row.v,
\t\t\tcount = row.c, sum = row.s, min = row.mn, max = row.mx,
\t\t})
\tend
\tfor id, count in pairs(state.players or {}) do
\t\tlocal playerId, name = string.match(id, "^(.-)" .. SEP .. "(.*)$")
\t\tif playerId then table.insert(players, { playerId = playerId, name = name, count = count }) end
\tend
\tfor id, count in pairs(state.cells or {}) do
\t\tlocal name, gx, gz = string.match(id, "^(.-)" .. SEP .. "(-?%d+)" .. SEP .. "(-?%d+)$")
\t\tif name then table.insert(cells, { name = name, gx = tonumber(gx), gz = tonumber(gz), count = count }) end
\tend
\treturn { counters = counters, players = players, cells = cells, samples = samples or {}, cell = mapCell }
end

-- Backoff: when RoSignal says slow down (429) or is having a bad moment (5xx)
-- this server stops sending for a while instead of hammering it.
local backoffUntil = 0
local backoffStep = 0

local function send(payload, ignoreBackoff)
\tif not ignoreBackoff and os.time() < backoffUntil then return false end
\tlocal ok, res = pcall(function()
\t\treturn HttpService:RequestAsync({
\t\t\tUrl = AGG_URL,
\t\t\tMethod = "POST",
\t\t\tHeaders = { ["Content-Type"] = "application/json", ["x-rosignal-key"] = GAME_KEY },
\t\t\tBody = HttpService:JSONEncode(payload),
\t\t})
\tend)
\tif not ok or type(res) ~= "table" then
\t\tbackoffStep = math.min(backoffStep + 1, 6)
\t\tbackoffUntil = os.time() + math.min(300, 15 * (2 ^ (backoffStep - 1)))
\t\treturn false
\tend
\tif res.StatusCode == 429 or res.StatusCode >= 500 then
\t\tbackoffStep = math.min(backoffStep + 1, 6)
\t\tbackoffUntil = os.time() + math.min(300, 15 * (2 ^ (backoffStep - 1)))
\t\treturn false
\tend
\tbackoffStep = 0
\treturn true
end

-- Hand a closed minute to MemoryStore so every server's counts merge into one
-- summary. If MemoryStore is unavailable (Studio, quota) we send our own share
-- directly — the counts still add up, they just cost one more request.
local function flushBucket(bucket, state, closing)
\tlocal samples = state.samples
\tstate.samples = nil
\t-- On shutdown there is nobody left to ship the merged minute later, so this
\t-- server posts its own share right away instead of parking it in MemoryStore.
\tif closing then
\t\tsend(encode(bucket, state, samples), true)
\t\treturn
\tend
\tif store then
\t\tlocal ok = pcall(function()
\t\t\tstore:UpdateAsync("b" .. bucket, function(old)
\t\t\t\treturn mergeState(old or { counters = {}, players = {}, cells = {} }, state)
\t\t\tend, 900)
\t\tend)
\t\tif ok then
\t\t\tawaitingSend[bucket] = os.time() + SEND_DELAY
\t\t\tif samples and #samples > 0 then
\t\t\t\tsend({ counters = {}, players = {}, cells = {}, samples = samples, cell = mapCell })
\t\t\tend
\t\t\treturn
\t\tend
\tend
\tsend(encode(bucket, state, samples))
end

-- Exactly one server sends each merged minute: whoever claims the flag first.
local function trySend(bucket, closing)
\tif not store then return true end
\tlocal claimed = false
\tlocal ok = pcall(function()
\t\tstore:UpdateAsync("s" .. bucket, function(old)
\t\t\tif old ~= nil then return nil end
\t\t\tclaimed = true
\t\t\treturn 1
\t\tend, 1800)
\tend)
\tif not ok then return false end
\tif not claimed then return true end

\tlocal merged = nil
\tpcall(function() merged = store:GetAsync("b" .. bucket) end)
\tif merged then
\t\t-- Only forget the merged minute once RoSignal has actually taken it,
\t\t-- so a backoff or outage retries instead of losing the counts.
\t\tif not send(encode(bucket, merged, nil), closing) then return false end
\t\tpcall(function() store:RemoveAsync("b" .. bucket) end)
\tend
\treturn true
end

local function tick()
\tlocal current = bucketNow()
\tfor bucket, state in pairs(pending) do
\t\tif bucket < current then
\t\t\tpending[bucket] = nil
\t\t\tflushBucket(bucket, state)
\t\tend
\tend
\tlocal now = os.time()
\tfor bucket, due in pairs(awaitingSend) do
\t\tif now >= due then
\t\t\tif trySend(bucket) then awaitingSend[bucket] = nil end
\t\tend
\tend
end

task.spawn(function()
\twhile true do
\t\ttask.wait(FLUSH_SECONDS)
\t\tpcall(tick)
\tend
end)

-- Shutdown: Roblox gives us roughly 30 seconds. Send everything we are holding
-- (including the minute still open) straight to RoSignal, then try to ship any
-- merged minute that was still waiting on its delay. Never error, never hang.
game:BindToClose(function()
\tlocal deadline = os.clock() + 20
\tpcall(function()
\t\tfor bucket, state in pairs(pending) do
\t\t\tpending[bucket] = nil
\t\t\tflushBucket(bucket, state, true)
\t\t\tif os.clock() > deadline then return end
\t\tend
\tend)
\tpcall(function()
\t\tfor bucket in pairs(awaitingSend) do
\t\t\tawaitingSend[bucket] = nil
\t\t\ttrySend(bucket, true)
\t\t\tif os.clock() > deadline then return end
\t\tend
\tend)
end)

local function trackInternal(name, props, player, options)
\tif type(name) ~= "string" or name == "" then return end
\tlocal bucket = bucketNow()
\tlocal state = stateFor(bucket)

\tbumpCounter(state, name, "", "", nil)

\tlocal keys = 0
\tif type(props) == "table" then
\t\tfor key, value in pairs(props) do
\t\t\tif keys >= MAX_PROP_KEYS then break end
\t\t\tkeys += 1
\t\t\tlocal numeric = type(value) == "number" and value or nil
\t\t\tbumpCounter(state, name, tostring(key), string.sub(tostring(value), 1, 120), numeric)
\t\tend
\tend

\tlocal userId = nil
\tif player then
\t\tuserId = tostring(typeof(player) == "Instance" and player.UserId or player)
\t\tlocal id = userId .. SEP .. name
\t\tstate.players[id] = (state.players[id] or 0) + 1

\t\tif wantsMap(name, options) then
\t\t\tlocal character = typeof(player) == "Instance" and player.Character or nil
\t\t\tlocal root = character and character:FindFirstChild("HumanoidRootPart")
\t\t\tif root then
\t\t\t\tlocal gx = math.floor(root.Position.X / mapCell)
\t\t\t\tlocal gz = math.floor(root.Position.Z / mapCell)
\t\t\t\tlocal id2 = name .. SEP .. gx .. SEP .. gz
\t\t\t\tstate.cells[id2] = (state.cells[id2] or 0) + 1
\t\t\tend
\t\tend
\tend

\t-- A thin slice is kept whole so you can still read real examples.
\tif (fullEvents[name] or (sampleRate > 0 and math.random() < sampleRate)) and #state.samples < 200 then
\t\tlocal sample = { name = name, props = props or {} }
\t\tif userId then sample.playerId = userId end
\t\ttable.insert(state.samples, sample)
\tend
end

--- Report something that happened. Player is optional and adds position.
--- Pass { map = false } as a fourth argument to leave this event off the map.
--- Never errors: if anything is wrong the event is dropped, your game runs on.
function RoSignal.Track(name, props, player, options)
\tpcall(trackInternal, name, props, player, options)
end



-- 4. Group ranks --------------------------------------------------------------

--- Rank a player into a group role: RoSignal.SetRank(player, "Member").
--- Pass { roleId = "123" } instead of a name if you prefer ids, and
--- { onlyPromote = false } to allow demotions (promote-only by default).
--- Yields. Returns true, or false plus the reason — it never errors.
function RoSignal.SetRank(player, role, options)
\tlocal userId = tostring(typeof(player) == "Instance" and player.UserId or player)
\toptions = type(options) == "table" and options or {}

\tlocal body = { playerId = userId }
\tif type(role) == "table" then
\t\tbody.roleId = role.roleId and tostring(role.roleId) or nil
\t\tbody.roleName = role.roleName
\telseif tonumber(role) ~= nil then
\t\tbody.roleId = tostring(role)
\telse
\t\tbody.roleName = tostring(role)
\tend
\tif body.roleId == nil and body.roleName == nil then
\t\treturn false, "Pass a role name or roleId."
\tend
\tbody.onlyPromote = options.onlyPromote ~= false

\tlocal ok, res = pcall(function()
\t\treturn HttpService:RequestAsync({
\t\t\tUrl = GROUPS_URL,
\t\t\tMethod = "POST",
\t\t\tHeaders = { ["Content-Type"] = "application/json", ["x-rosignal-key"] = GAME_KEY },
\t\t\tBody = HttpService:JSONEncode(body),
\t\t})
\tend)
\tif not ok then
\t\treturn false, "Could not reach RoSignal."
\tend

\tlocal decoded = nil
\tpcall(function() decoded = HttpService:JSONDecode(res.Body) end)
\tif res.Success and type(decoded) == "table" and decoded.ok then
\t\treturn true, nil
\tend
\treturn false, (type(decoded) == "table" and decoded.error) or ("Rank change failed (" .. res.StatusCode .. ").")
end

return RoSignal
`;
}

export function handlersSource(): string {
  return `--[[ ${HANDLERS_NAME} — this is your file. Edit it freely.
\tIt is where your game reacts to RoSignal.

\tThree things happen below:
\t  1. Bind          run code whenever a live setting changes.
\t  2. OnAnnouncement  show messages you send from the site.
\t  3. Track         report something that happened, for Analytics.

\t${DEMO_NAME} (inside this script) is only a starter demo UI so your
\tfirst test is visible. Delete it and call your own game code instead.

\tEverything RoSignal can do: https://rosignal.app/docs ]]

local RoSignal = require(game.ServerScriptService.${MODULE_NAME})
local Demo = require(script.${DEMO_NAME})

-- Runs now with the current value, and again every time you change it on the site.
RoSignal.Bind("Multiplier", function(value)
\tDemo.SetMultiplier(value)
end)

-- Announcements sent from Messages, rules, or the guided setup.
RoSignal.OnAnnouncement(function(text)
\tDemo.Announce(text)
end)

-- Report something that happened, so it shows up in Analytics.
RoSignal.Track("ServerStarted", { placeId = game.PlaceId })
`;
}

/**
 * The starter demo UI, kept out of the developer's entry point so that file
 * stays three lines of real API. Written as a child of the handlers script and
 * safe to delete.
 */
export function demoSource(): string {
  return `--[[ ${DEMO_NAME} — starter demo UI only.

\tIt draws a small corner label and an announcement banner so your very
\tfirst RoSignal test is visible when you press Play. None of RoSignal
\tneeds it: delete this module and call your own game code from
\t${HANDLERS_NAME} whenever you are ready. ]]

local Players = game:GetService("Players")

local Demo = {}

local multiplier = 1

-- Build (or find) this player's demo screen. Server-created ScreenGuis live in
-- PlayerGui, which only exists once the player has loaded, so we wait for it.
local function screenFor(player)
\tif not player.Parent then return nil end
\tlocal gui = player:FindFirstChild("PlayerGui") or player:WaitForChild("PlayerGui", 10)
\tif not gui then return nil end

\tlocal screen = gui:FindFirstChild("${DEMO_NAME}")
\tif screen then return screen end

\tscreen = Instance.new("ScreenGui")
\tscreen.Name = "${DEMO_NAME}"
\tscreen.ResetOnSpawn = false
\tscreen.IgnoreGuiInset = true

\tlocal value = Instance.new("TextLabel")
\tvalue.Name = "Value"
\tvalue.Size = UDim2.fromScale(0.16, 0.05)
    value.Position = UDim2.fromScale(0.015, 0.3)
\tvalue.BackgroundColor3 = Color3.fromRGB(15, 17, 21)
\tvalue.BackgroundTransparency = 0.15
\tvalue.BorderSizePixel = 0
\tvalue.TextColor3 = Color3.fromRGB(255, 255, 255)
\tvalue.Font = Enum.Font.Gotham
\tvalue.TextScaled = true
\tvalue.Text = "Multiplier: " .. tostring(multiplier)
\tvalue.Parent = screen

\tlocal banner = Instance.new("TextLabel")
\tbanner.Name = "Banner"
\tbanner.AnchorPoint = Vector2.new(0.5, 0)
    banner.Size = UDim2.fromScale(0.38, 0.075)
    banner.Position = UDim2.fromScale(0.5, 0.16)
\tbanner.BackgroundColor3 = Color3.fromRGB(15, 17, 21)
\tbanner.BackgroundTransparency = 0.1
\tbanner.BorderSizePixel = 0
\tbanner.TextColor3 = Color3.fromRGB(255, 255, 255)
\tbanner.Font = Enum.Font.GothamBold
\tbanner.TextScaled = true
\tbanner.TextWrapped = true
\tbanner.Text = ""
\tbanner.Visible = false
\tbanner.Parent = screen

\tscreen.Parent = gui
\treturn screen
end

local function forEachScreen(fn)
\tfor _, player in ipairs(Players:GetPlayers()) do
\t\ttask.spawn(function()
\t\t\tlocal screen = screenFor(player)
\t\t\tif screen then fn(screen) end
\t\tend)
\tend
end

--- Show the current value of a live setting in the corner of the screen.
function Demo.SetMultiplier(value)
\tmultiplier = value == nil and 1 or value
\tforEachScreen(function(screen)
\t\tscreen.Value.Text = "Multiplier: " .. tostring(multiplier)
\tend)
end

local bannerToken = 0

--- Pop an announcement up for a few seconds, replacing any previous one.
function Demo.Announce(text)
\tbannerToken += 1
\tlocal token = bannerToken
\tforEachScreen(function(screen)
\t\tlocal banner = screen.Banner
\t\tbanner.Text = tostring(text)
\t\tbanner.Visible = true
\tend)
\ttask.delay(6, function()
\t\tif token ~= bannerToken then return end
\t\tforEachScreen(function(screen)
\t\t\tscreen.Banner.Visible = false
\t\tend)
\tend)
end

-- Players already in the server (Studio Play) and everyone who joins later.
Players.PlayerAdded:Connect(function(player)
\ttask.spawn(function()
\t\tlocal screen = screenFor(player)
\t\tif screen then screen.Value.Text = "Multiplier: " .. tostring(multiplier) end
\tend)
end)
forEachScreen(function(screen)
\tscreen.Value.Text = "Multiplier: " .. tostring(multiplier)
end)

return Demo
`;
}

/**
 * A settings module the developer owns. Written once at pairing time and never
 * overwritten, so their choices survive every plugin update.
 */
export function settingsSource(): string {
  return `--[[ RoSignal settings — this file is yours. The plugin never overwrites it.

\tMapByDefault  when true, events that include a player also send that
\t              player's position, so they appear on the Analytics map.
\tMapEvents     optional allow-list. When set, ONLY these events send a
\t              position, whatever MapByDefault says.
\tMapExclude    events that never send a position.

\tYou can also decide per call: RoSignal.Track(name, props, player, { map = false })
]]

return {
\tMapByDefault = true,
\tMapEvents = nil,
\tMapExclude = {},
}
`;
}
